name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-ci-job:
    runs-on: ubuntu-latest

    #https://github.com/actions/setup-python
    #https://github.com/actions/checkout
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Run Tests
      run: |
        python -m unittest test_calc.py -v